"""new fields in user model

Revision ID: 855bce4d7e86
Revises: 1bc4af511df5
Create Date: 2018-02-28 11:18:27.510883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855bce4d7e86'
down_revision = '1bc4af511df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
